lwcExperienceSite/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

lwcExperienceSite/main/default/objects/Residence__c/fields/Has_Garage__c.field-meta.xml
<CustomField>
    <fullName>Has_Garage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Garage</label>
    <type>Checkbox</type>
</CustomField>

lwcExperienceSite/main/default/objects/Residence__c/fields/Is_Vacant__c.field-meta.xml
<CustomField>
    <fullName>Is_Vacant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Vacant</label>
    <type>Checkbox</type>
</CustomField>

lwcExperienceSite/main/default/objects/Residence__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

lwcExperienceSite/main/default/objects/Residence__c/fields/number_of_baths__c.field-meta.xml
<CustomField>
    <fullName>number_of_baths__c</fullName>
    <label># of Baths</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

lwcExperienceSite/main/default/objects/Residence__c/fields/number_of_beds__c.field-meta.xml
<CustomField>
    <fullName>number_of_beds__c</fullName>
    <label># of Beds</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

lwcExperienceSite/main/default/classes/PropertyManagementHelper.cls
public with sharing class PropertyManagementHelper {
    public PropertyManagementHelper() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Residence__c> getAllLocationNamesWithVacantResidences(){
        try {
            return [SELECT Name, Is_Vacant__c, Location__r.Name, Location__c FROM Residence__c WHERE Is_Vacant__c = true];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}




/*

query for reference

gets all locations and unit data
SELECT Name, LocationType, (SELECT Name, number_of_baths__c, number_of_beds__c, Has_Garage__c, Is_Vacant__c FROM Residences__r) FROM Location

*/